version: 2
jobs:
  build:
    docker:
      - image: athos/cljc-dev:openjdk-8-alpine-20190219-0

    working_directory: ~/repo

    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run: clojure -A:check:test:cljs -Stree

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gitlibs
          key: v1-dependencies-{{ checksum "deps.edn" }}

      - run:
          name: check
          command: clojure -A:check

      - run:
          name: test CLJ
          command: clojure -A:test

      - run:
          name: test CLJS
          command: clojure -Acljs:test:test-cljs
