name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Setup Clojure CLI & Babashka
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: latest
        bb: latest
    - name: Cache deps
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2
          ~/.gitlibs
          .cpcache
        key: ${{ runner.os }}-${{ hashFiles('deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Install deps
      run: |
        clojure -A:check:test:cljs:coverage -P
    - name: Run check
      run: clojure -M:check:cljs
    - name: Run tests for CLJ 1.11
      run: clojure -M:test
    - name: Run tests for CLJ 1.10
      run: clojure -M:1.10:test
    - name: Run tests for CLJ 1.9
      run: clojure -M:1.9:test
    - name: Run tests for CLJ 1.8
      run: clojure -M:1.8:test
    - name: Run CLJS tests on Node
      run: clojure -M:test:cljs:test-cljs
    - name: Run tests on Babashka
      run: bb test
    - name: Measure test coverage
      run: clojure -A:test:coverage
    - name: Upload coverage report to CodeCov
      uses: codecov/codecov-action@v3
